# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 504)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(".QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 15px;\n"
"    border: 1px solid blue;\n"
"}\n"
".QPushButton:hover {\n"
"    background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"    border-radius: 15px;\n"
"    border: 1px solid blue;\n"
"}\n"
".QLineEdit {\n"
"    background-color: transparent;\n"
"    border-radius: 15px;\n"
"    border: 1px solid blue;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.ahkbhopLabel = QtWidgets.QLabel(self.centralwidget)
        self.ahkbhopLabel.setGeometry(QtCore.QRect(10, 20, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ahkbhopLabel.setFont(font)
        self.ahkbhopLabel.setStyleSheet("background-color: transparent;")
        self.ahkbhopLabel.setObjectName("ahkbhopLabel")
        self.ahkbhopButton = QtWidgets.QPushButton(self.centralwidget)
        self.ahkbhopButton.setGeometry(QtCore.QRect(520, 10, 81, 41))
        self.ahkbhopButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ahkbhopButton.setFont(font)
        self.ahkbhopButton.setStyleSheet("")
        self.ahkbhopButton.setObjectName("ahkbhopButton")
        self.crorsshairLabel = QtWidgets.QLabel(self.centralwidget)
        self.crorsshairLabel.setGeometry(QtCore.QRect(10, 70, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.crorsshairLabel.setFont(font)
        self.crorsshairLabel.setStyleSheet("background-color: transparent;")
        self.crorsshairLabel.setObjectName("crorsshairLabel")
        self.crosshairButton = QtWidgets.QPushButton(self.centralwidget)
        self.crosshairButton.setGeometry(QtCore.QRect(520, 60, 81, 41))
        self.crosshairButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.crosshairButton.setFont(font)
        self.crosshairButton.setStyleSheet("")
        self.crosshairButton.setObjectName("crosshairButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hax No Hax Pack"))
        self.ahkbhopLabel.setText(_translate("MainWindow", "AHK BHhop"))
        self.ahkbhopButton.setText(_translate("MainWindow", "On"))
        self.crorsshairLabel.setText(_translate("MainWindow", "Sniper Crosshair"))
        self.crosshairButton.setText(_translate("MainWindow", "On"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
